export const MOCK_CAMPAIGNS = [
	{
		id: "camp-1",
		title: "Summer Collection Launch",
		thumbnail: "https://picsum.photos/400/250?random=1",
		budgetTotal: 5000,
		budgetSpent: 3200,
		deadline: "2026-05-15",
		type: "REEL" as const,
		brandName: "Zara",
	},
	{
		id: "camp-2",
		title: "Brand Identity Redesign",
		thumbnail: "https://picsum.photos/400/250?random=2",
		budgetTotal: 2500,
		budgetSpent: 800,
		deadline: "2026-06-01",
		type: "LOGO" as const,
		brandName: "FreshBrew Co.",
	},
	{
		id: "camp-3",
		title: "Fitness App Promo",
		thumbnail: "https://picsum.photos/400/250?random=3",
		budgetTotal: 8000,
		budgetSpent: 6500,
		deadline: "2026-04-30",
		type: "REEL" as const,
		brandName: "FitLife",
	},
	{
		id: "camp-4",
		title: "Restaurant Logo Refresh",
		thumbnail: "https://picsum.photos/400/250?random=4",
		budgetTotal: 1500,
		budgetSpent: 1500,
		deadline: "2026-05-20",
		type: "LOGO" as const,
		brandName: "Sakura Kitchen",
	},
] as const;

export const MOCK_VIDEOS = [
	{
		id: "vid-1",
		thumbnail: "https://picsum.photos/400/600?random=10",
		username: "emma.creates",
		timeAgo: "2h ago",
		campaignName: "Summer Collection Launch",
		views: "122.0k",
		likes: "12.0k",
	},
	{
		id: "vid-2",
		thumbnail: "https://picsum.photos/400/600?random=11",
		username: "jake.films",
		timeAgo: "5h ago",
		campaignName: "Fitness App Promo",
		views: "89.3k",
		likes: "7.2k",
	},
	{
		id: "vid-3",
		thumbnail: "https://picsum.photos/400/600?random=12",
		username: "sophia.visuals",
		timeAgo: "1d ago",
		campaignName: "Summer Collection Launch",
		views: "45.1k",
		likes: "3.8k",
	},
	{
		id: "vid-4",
		thumbnail: "https://picsum.photos/400/600?random=13",
		username: "marcus.edit",
		timeAgo: "1d ago",
		campaignName: "Fitness App Promo",
		views: "210.5k",
		likes: "18.4k",
	},
	{
		id: "vid-5",
		thumbnail: "https://picsum.photos/400/600?random=14",
		username: "lily.content",
		timeAgo: "3d ago",
		campaignName: "Brand Identity Redesign",
		views: "33.7k",
		likes: "2.1k",
	},
	{
		id: "vid-6",
		thumbnail: "https://picsum.photos/400/600?random=15",
		username: "noah.reels",
		timeAgo: "4d ago",
		campaignName: "Restaurant Logo Refresh",
		views: "67.9k",
		likes: "5.6k",
	},
] as const;
